#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# log
echo ""
echo -e "\x1b[1;35m[pre-push]\x1b[0m: Start git-hooks via husky@^8.0.3..."

echo -e "\x1b[1;90m$ npx frogagu pre-git-push\x1b[0m" 
npx frogagu pre-git-push
